version: '2.2'
#https://www.elastic.co/guide/en/elasticsearch/reference/current/certgen.html
services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    command: >
      bash -c '
      yum install -y -q -e 0 unzip;
      if [[ ! -f /certs/bundle.zip ]]; then
        bin/elasticsearch-certutil cert --silent --pem --in config/certificates/http_instances.yml -out /certs/bundle.zip;
        unzip /certs/bundle.zip -d /certs; 
      fi;
      chown -R 1000:0 /certs'
    user: "0"
     ing_dir: /usr/share/elasticsearch
    volumes: ['http_certs:/certs', '.:/usr/share/elasticsearch/config/certificates']

volumes:
  http_certs:
    driver: local
    driver_opts:
      type: none
      device: $PWD/${HOST_DATA_PATH}/http_certs
      o: bind