
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - mkdir -p .public/{hashed_folder}
    - mv index.html .public/index.html
    - mv grunge_patterns.jpg .public/grunge_patterns.jpg
    - cp -r build/* .public/{hashed_folder}
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master

